language: java
jdk:
- oraclejdk8
install: echo "skip 'gradle assemble' step"
script: ./gradlew build
before_install:
- chmod +x gradlew
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/