# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:10-jdk

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m # JVM maximum heap limit

    steps:
      - run: pwd
      - checkout
      - run: ./gradlew clean build